# Generated by Django 4.2.7 on 2023-12-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0003_alter_todolist_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='description',
            field=models.TextField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
