# Generated by Django 4.1.12 on 2023-12-08 14:29

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('things', '0005_comment_comment_things_comm_created_5c0ab8_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
